### ISSUE TITLE
 Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by Sinosaurus** [DesignRevision/shards-vue#11]
## Expected Behavior
```
$ vue serve sandbox/Sandbox.vue
(node:10408) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'version' of undefined
    at module.exports (C:\Users\DELL\AppData\Roaming\npm\node_modules\@vue\cli-service-global\node_modules\@vue\cli-plugin-eslint\index.js:18:29)
    at plugins.forEach (C:\Users\DELL\AppData\Roaming\npm\node_modules\@vue\cli-service-global\node_modules\@vue\cli-service\lib\Service.js:79:7)
    at Array.forEach (<anonymous>)
    at Service.init (C:\Users\DELL\AppData\Roaming\npm\node_modules\@vue\cli-service-global\node_modules\@vue\cli-service\lib\Service.js:78:18)
    at Service.run (C:\Users\DELL\AppData\Roaming\npm\node_modules\@vue\cli-service-global\node_modules\@vue\cli-service\lib\Service.js:204:10)
    at Object.exports.serve (C:\Users\DELL\AppData\Roaming\npm\node_modules\@vue\cli-service-global\index.js:54:33)
    at Command.program.command.description.option.option.action (C:\Users\DELL\AppData\Roaming\npm\node_modules\@vue\cli\bin\vue.js:102:53)
    at Command.listener (C:\Users\DELL\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\commander\index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
(node:10408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. Done in 0.57s.
```

## Current Behavior
```
 npm i @vue/cli-service-global@3.0.0 -g
```

**Comment by hisk** [comment]
Hello @Sinosaurus ! I apologise for the huge delay.

Using which version of node and npm are you experiencing this issue? 😄

**Comment by Sinosaurus** [comment]
Hi, @hisk 
`node -- v10.15.0`
`npm --  6.4.1`

> `npm run watch`

**Comment by hisk** [comment]
@Sinosaurus I apologize again for the huge delay. 😅

I checked in more depth and this issue seems to be caused by [vue-cli](https://github.com/vuejs/vue-cli/issues/2866) and an official fix has already been provided. Please make sure to update vue-cli to the latest version, or attempt to use the workaround of installing `eslint` as stated in the issue mentioned above.

Please let me know how it goes. I am waiting for your feedback.
